// Copied from the current temp/humid route pages as an additive scaffold.

export const ALL_SENSORS = [
  { id: "aoi", areaId: "P1F1-04", lineName: "AOI", floorSlug: "p1f1", group: "Sensors" },
  { id: "dipping2", areaId: "P1F1-06", lineName: "Dipping2", floorSlug: "p1f1", group: "Sensors" },
  { id: "dipping", areaId: "P1F1-01", lineName: "Dipping", floorSlug: "p1f1", group: "Sensors" },
  { id: "server-room", areaId: "P1F1-03", lineName: "Server Room", floorSlug: "p1f1", group: "Sensors" },
  { id: "smt", areaId: "P1F1-02", lineName: "SMT", floorSlug: "p1f1", group: "Sensors" },
  { id: "smt-cs", areaId: "P1F1-10", lineName: "SMT - Cold Storage", floorSlug: "p1f1", group: "Sensors" },
  { id: "smt-mh", areaId: "P1F1-05", lineName: "SMT MH", floorSlug: "p1f1", group: "Sensors" },
  { id: "smt-mh-rcv", areaId: "P1F1-14", lineName: "SMT MH Receiving", floorSlug: "p1f1", group: "Sensors" },
  { id: "bga-r", areaId: "P1F1-15", lineName: "BGA Rework", floorSlug: "p1f1", group: "Sensors" },
  { id: "coating", areaId: "P1F1-17", lineName: "Coating Area", floorSlug: "p1f1", group: "Sensors" },
  { id: "dess-1", areaId: "P1F1-09", lineName: "SMT MH Dessicator 1", floorSlug: "p1f1", group: "Dessicators" },
  { id: "dess-2", areaId: "P1F1-07", lineName: "SMT MH Dessicator 2", floorSlug: "p1f1", group: "Dessicators" },
  { id: "dess-3", areaId: "P1F1-11", lineName: "SMT MH Dessicator 3", floorSlug: "p1f1", group: "Dessicators" },
  { id: "dess-4", areaId: "P1F1-12", lineName: "SMT MH Dessicator 4", floorSlug: "p1f1", group: "Dessicators" },
  { id: "dess-5", areaId: "P1F1-13", lineName: "SMT MH Dessicator 5", floorSlug: "p1f1", group: "Dessicators" },
  { id: "brother-assy-1", areaId: "P1F2-03", lineName: "Brother Assy 1", floorSlug: "p1f2", group: "Sensors" },
  { id: "brother-assy-2", areaId: "P1F2-02", lineName: "Brother Assy 2", floorSlug: "p1f2", group: "Sensors" },
  { id: "jcm-pcba", areaId: "P1F2-01", lineName: "JCM PCBA", floorSlug: "p1f2", group: "Sensors" },
  { id: "mh-brother-pkg", areaId: "P1F2-05", lineName: "MH Brother Packaging", floorSlug: "p1f2", group: "Sensors" },
  { id: "fg", areaId: "P2F1-03", lineName: "FG", floorSlug: "p2f1", group: "Sensors" },
  { id: "wh-office", areaId: "P2F1-01", lineName: "Warehouse Office", floorSlug: "p2f1", group: "Sensors" },
  { id: "wh-cs", areaId: "P2F1-16", lineName: "WH-Cold Storage", floorSlug: "p2f1", group: "Sensors" },
  { id: "wh-cs2", areaId: "P2F1-17", lineName: "WH-Cold Storage 2", floorSlug: "p2f1", group: "Sensors" },
  { id: "wo-north", areaId: "P2F1-18", lineName: "WO-North", floorSlug: "p2f1", group: "Sensors" },
  { id: "wo-south-ha", areaId: "P2F1-07", lineName: "WO-South - Holding Area", floorSlug: "p2f1", group: "Sensors" },
  { id: "wo-sw-iqc", areaId: "P2F1-04", lineName: "WO-S-West-IQC", floorSlug: "p2f1", group: "Sensors" },
  { id: "wo-w-south-qa", areaId: "P2F1-05", lineName: "WO-W South-QA", floorSlug: "p2f1", group: "Sensors" },
  { id: "facility", areaId: "P2F1-06", lineName: "Facilities", floorSlug: "p2f1", group: "Sensors" },
  { id: "calibration-room", areaId: "P2F2-04", lineName: "Calibration Room", floorSlug: "p2f2", group: "Sensors" },
  { id: "jcm-assy", areaId: "P2F2-01", lineName: "JCM Assy", floorSlug: "p2f2", group: "Sensors" },
  { id: "wh-brother-pkg", areaId: "P2F2-02", lineName: "WH Brother Packaging", floorSlug: "p2f2", group: "Sensors" },
  { id: "wh-mh-jcm-assy", areaId: "P2F2-03", lineName: "WH-MH JCM Assy", floorSlug: "p2f2", group: "Sensors" },
  { id: "cis", areaId: "P1F1-16", lineName: "CIS", floorSlug: "p2f2", group: "Sensors" },
  { id: "p1p2-bridge", areaId: "P1F2-06", lineName: "P1P2_Bridge", floorSlug: "p12f2", group: "Sensors" },
  { id: "wh-a", areaId: "P2F1-08", lineName: "WH - A", floorSlug: "wh", group: "Sensors" },
  { id: "wh-b", areaId: "P2F1-09", lineName: "WH - B", floorSlug: "wh", group: "Sensors" },
  { id: "wh-c", areaId: "P2F1-10", lineName: "WH - C", floorSlug: "wh", group: "Sensors" },
  { id: "wh-d", areaId: "P2F1-11", lineName: "WH - D", floorSlug: "wh", group: "Sensors" },
  { id: "wh-e", areaId: "P2F1-12", lineName: "WH - E", floorSlug: "wh", group: "Sensors" },
  { id: "wh-f", areaId: "P2F1-13", lineName: "WH - F", floorSlug: "wh", group: "Sensors" },
  { id: "wh-g", areaId: "P2F1-14", lineName: "WH - G", floorSlug: "wh", group: "Sensors" },
  { id: "wh-h", areaId: "P2F1-15", lineName: "WH - H", floorSlug: "wh", group: "Sensors" },
];

export const DEFAULT_LIMITS = { tempUL: 28, tempLL: 13, humidUL: 80, humidLL: 40 };

export const ALL_EDITABLE_SENSORS = ALL_SENSORS.map((sensor) => ({
  id: sensor.id,
  name: sensor.lineName,
  areaId: sensor.areaId,
  group: sensor.group,
}));
